default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PSWD"] %>
  host: <%= ENV["DB_SERVER"] %>

development:
  <<: *default
  database: system-due-date_development
test:
  <<: *default
  database: system-due-date_test
production:
  <<: *default
  database: system-due-date_production